GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "React patterns",
    "author":  "Michael Chan",
    "url": "https://reactpatterns.com/",
    "likes": 0
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Go To Statement Considered Harmful",
    "author": "Edsger W. Dijkstra",
    "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
    "likes": 0
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Like oletus-testi",
    "author": "anonyymi",
    "url": "www.yle.fi"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Like oletus-testi",
    "author": "anonyymi",
    "url": "www.yle.fi",
    "likes": "ei luku"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Parsing Html The Cthulhu Way",
    "author": "Jeff Atwood",
    "url": "https://blog.codinghorror.com/parsing-html-the-cthulhu-way/",
    "likes": 1234
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Ei url",
    "author": "anonyymi"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "author": "ei titleä",
     "url": "www.yle.fi"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "author": "ei titleä eikä url"
}

###
DELETE http://localhost:3003/api/blogs/643803923ed7050a4a8b463b

###
PUT http://localhost:3003/api/blogs/64351a57b0cfedec724f975a
Content-Type: application/json

{
    "title": "Muokattu PUT",
    "author": "Muokdattu PUT",
    "url": "Muokattu PUT"
}

###
PUT http://localhost:3003/api/blogs/64351a57b0cfedec724f975a
Content-Type: application/json

{
    "title": "Muokattu PUT",
    "author": "Muokdattu PUT",
    "url": "Muokattu PUT",
    "likes": 12
}


###
PUT http://localhost:3003/api/blogs/64351a57b0cfedec724f975a
Content-Type: application/json

{
    "title": "Muokattu PUT",
    "author": "Muokdattu PUT",
    "url": "Muokattu PUT",
    "likes": "lol"
}

###
PUT http://localhost:3003/api/blogs/64351a57b0cfedec724f975a
Content-Type: application/json

{
    "title": "",
    "author": "Muokdattu PUT",
    "url": "Muokattu PUT"
}

###
PUT http://localhost:3003/api/blogs/64351a57b0cfedec724f975a
Content-Type: application/json

{
    "title": null,
    "author": "Muokdattu PUT",
    "url": "Muokattu PUT"
}

###
PUT http://localhost:3003/api/blogs/64351a57b0cfedec724f975a
Content-Type: application/json

{
    "title": null
}

###
PUT http://localhost:3003/api/blogs/64351a57b0cfedec724f975a
Content-Type: application/json

{
    "title": "Muokattu PUT",
    "author": "Muokdattu PUT",
    "url": ""
}
