name: Bloglist CI/CD pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

env:
  PORT: 3000
  BACKEND_PORT: 3003
  TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
  SECRET: ${{ secrets.SECRET }}
  STEP_INFO: ''

jobs:
  test_and_build_bloglist:
    name: Tests and builds the Bloglist application
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        id: install_dependencies
        run: |
          echo "STEP_INFO='Install dependencies'" >> "$GITHUB_ENV"
          npm install

      - name: Test backend
        id: test_backend
        run: |
          echo "STEP_INFO='Test backend'" >> "$GITHUB_ENV"
          npm test

      - name: Test frontend
        id: test_frontend
        run: |
          echo "STEP_INFO='Test frontend'" >> "$GITHUB_ENV"
          npm run test:react

      - name: Check style
        id: check_style
        run: |
          echo "STEP_INFO='Check style'" >> "$GITHUB_ENV"
          npm run eslint

      - name: Build
        id: build
        run: |
          echo "STEP_INFO='Build'" >> "$GITHUB_ENV"
          npm run build

      - name: Check failing step (push)
        # if: ${{ failure() && github.event_name == 'push' }}
        if: failure()
        # run: echo Failing step ${{ env.STEP_INFO }}
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        with:
          severity: error
          description: '${{ env.STEP_INFO }} failed - :crying_cat_face:'
          details: 'Broken commit: ${{ github.event.head_commit.url }} ${{ github.event_name }} ${{ github.event.action }} by ${{ github.actor }}'
          text: '${{ github.event.repository.full_name }}: ${{ env.STEP_INFO }} failed'
          webhookUrl: ${{ secrets.OMA_DISCORD_WEBHOOK }}

      - name: Check failing step (pull request opened)
        if: ${{ failure() && github.event_name == 'pull_request' && github.event.action == 'opened' }}
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        with:
          severity: error
          description: '${{ env.STEP_INFO }} failed ${{ github.event_name }} ${{ github.event.action }} - :crying_cat_face:'
          details: 'Pull Request opened with failed checks! Broken commit: ${{ github.event.pull_request.base.repo.html_url }}/commit/${{ github.event.pull_request.head.sha }} by ${{ github.actor }}'
          text: '${{ github.event.repository.full_name }}: ${{ env.STEP_INFO }} failed'
          webhookUrl: ${{ secrets.OMA_DISCORD_WEBHOOK }}

      - name: Check failing step (pull request synchronize)
        if: ${{ failure() && github.event_name == 'pull_request' && github.event.action == 'synchronize' }}
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        with:
          severity: error
          description: '${{ env.STEP_INFO }} failed ${{ github.event_name }} ${{ github.event.action }} - :crying_cat_face:'
          details: 'Pull Request synch with failed checks! Broken commit: ${{ github.event.pull_request.base.repo.html_url }}/commit/${{ github.event.pull_request.head.sha }} by ${{ github.actor }}'
          text: '${{ github.event.repository.full_name }}: ${{ env.STEP_INFO }} failed'
          webhookUrl: ${{ secrets.OMA_DISCORD_WEBHOOK }}

  e2e_tests_on_build:
    name: Builds and runs E2E tests on Bloglist application
    runs-on: ubuntu-22.04
    needs: test_and_build_bloglist
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: E2E tests with Cypress
        uses: cypress-io/github-action@v5
        with:
          command: 'npm run test:e2e'
          start: 'npm run start:test-build'
          wait-on: http://localhost:3003

  deploy_on_render:
    name: Deploys bloglist application on render.com
    if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)), '#skip') }}
    runs-on: ubuntu-22.04
    needs: [test_and_build_bloglist, e2e_tests_on_build]
    steps:
      - uses: shamaanikala/use-render-deploy@v1-alpha
        with:
          render-service-id: ${{ secrets.RENDER_SERVICE_ID }}
          render-api-key: ${{ secrets.RENDER_API_KEY }}
      - name: Notify deploy action succesful (own dev discord)
        if: ${{ success() }}
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        with:
          severity: info
          description: 'Deploying new version of Bloglist :rocket: '
          details: 'to: ${{ vars.RENDER_DEPLOYED_URL }}'
          text: Deploying new version of Bloglist to render.com...
          webhookUrl: ${{ secrets.OMA_DISCORD_WEBHOOK }}

  tag_release:
    name: Bumb the version number (tag)
    needs: [test_and_build_bloglist, e2e_tests_on_build, deploy_on_render]
    if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)), '#skip') }}
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Bumb version and push tag
        uses: anothrNick/github-tag-action@a2c70ae13a881faf2b4953baaa9e49731997ab36
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
