name: Bloglist CI/CD pipeline

on:
  push:
    branches:
      - master

env:
  PORT: 3000
  BACKEND_PORT: 3003
  TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
  SECRET: ${{ secrets.SECRET }}

jobs:
  test_and_build_bloglist:
    name: Tests and builds the Bloglist application
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install

      - name: Check style
        run: npm run eslint

      - name: Test backend
        run: npm test

      - name: Test frontend
        run: npm run test:react

      - name: Build
        run: npm run build

  e2e_tests_on_build:
    name: Tests and builds the Bloglist application
    runs-on: ubuntu-22.04
    needs: test_and_build_bloglist
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Run the built app with NODE_ENV=test
        run: 'npm run start:test-build'
      - name: E2E tests with Cypress
        run: 'npm run test:e2e'
