name: Bloglist CI/CD pipeline

on:
  push:
    branches:
      - master

env:
  PORT: 3000
  BACKEND_PORT: 3003
  TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
  SECRET: ${{ secrets.SECRET }}

jobs:
  test_and_build_pipeline:
    name: Tests and builds the Bloglist application
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install

      - name: Check style
        run: npm run eslint

      - name: Test backend
        #run: npm test # this step is succesful even if tests fail
        #shell: bash # trying to fix the false success with this, does not work
        run: 'npm run test:backend-file -- tests/login_api.test.js' # failing test

      - name: Test frontend
        run: npm run test:react

      - name: Build
        run: npm run build
